### PR TITLE
Send notifications when IPR check fails

### LINKED ISSUE #27: Feature request: notification system. If a check fails, ash-nazg should notify whoever is listed in w3c.json.

### PR DESCRIPTION
**Pull request by dontcallmedom**
close #27

### CODE REVIEW

**Comment by tripu** [comment]
@dontcallmedom:

```
server.js:722
    var transporter = nodemailer.createTransport(sendmailTransport(options))
                                                                   ^
ReferenceError: options is not defined
    at Object.<anonymous> (server.js:722:68)
```

Did you forget to commit something?

**Comment by dontcallmedom** [comment]
fixed

**Comment by tripu** [comment]
@dontcallmedom, now I see an error [in line 189 of `gh.js`](https://github.com/w3c/ash-nazg/pull/32/files#diff-0577d6043f6efc7fba5127ec5f38ed16R189):

```
error:  TypeError: Cannot read property 'map' of undefined
    at gh.js:189:48
```

Don't you need to read `w3cinfo.content`, base64-decode it, then access `contacts`?

**Comment by dontcallmedom** [comment]
@tripu can you say more of the context in which you see that error?

the base64 decoding is normally done by octokat directly, and the test suite should have caught it otherwise. It looks like you're hitting a repo with a w3c.json that doesn't have a `contacts` property; clearly ash-nazg should not crash on such a situation, but I would like to confirm this is indeed the problem before patching it.

**Comment by tripu** [comment]
@dontcallmedom, I'm testing right now with `tripu/foo`: [`https://github.com/tripu/foo/blob/master/w3c.json`](https://github.com/tripu/foo/blob/master/w3c.json) is the file (I haven't changed it since ash-nazg added it to the repo).

`w3cinfo` looks like this:

```js
{ name: 'w3c.json',
  path: 'w3c.json',
  sha: '8048ee49b875f0f30308f886f62dda56c4f23249',
  size: 84,
  url: 'https://api.github.com/repos/tripu/foo/contents/w3c.json?ref=master',
  html: { [Function] url: 'https://github.com/tripu/foo/blob/master/w3c.json' },
  htmlUrl: 'https://github.com/tripu/foo/blob/master/w3c.json',
  git: 
   { [Function]
     url: 'https://api.github.com/repos/tripu/foo/git/blobs/8048ee49b875f0f30308f886f62dda56c4f23249' },
  gitUrl: 'https://api.github.com/repos/tripu/foo/git/blobs/8048ee49b875f0f30308f886f62dda56c4f23249',
  download: 
   { [Function]
     url: 'https://raw.githubusercontent.com/tripu/foo/master/w3c.json' },
  downloadUrl: 'https://raw.githubusercontent.com/tripu/foo/master/w3c.json',
  type: 'file',
  content: 'IHsKICAgICJncm91cCI6ICAgICAgWyI1Mzc5MSJdCiwgICAiY29udGFjdHMi\nOiAgIFsidHJpcHUiXQosICAgInNob3J0TmFtZSI6ICAiZm9vIgp9\n',
  encoding: 'base64',
  Links: 
   { self: 'https://api.github.com/repos/tripu/foo/contents/w3c.json?ref=master',
     git: 'https://api.github.com/repos/tripu/foo/git/blobs/8048ee49b875f0f30308f886f62dda56c4f23249',
     html: 'https://github.com/tripu/foo/blob/master/w3c.json' },
  fetch: [Function],
  read: [Function],
  readBinary: [Function],
  remove: [Function],
  create: [Function],
  update: [Function],
  add: [Function],
  contains: [Function] }
```

The properties of the JSON file aren't in the object returned by `octokat`. But if you decode `content`, it gives you the right content of the file.

**Comment by dontcallmedom** [comment]
Oh, I see, I have confused myself by wrongly mocking the Github API call in my test case. Thanks a lot for spotting that bug @tripu !

I'll bring a patch tomorrow.

**Comment by dontcallmedom** [comment]
@tripu pull request updated

**Comment by tripu** [comment]
Thanks, @dontcallmedom. A few suggestions, after a while messing around:

Can you edit `README.md` and/or `DEVELOPMENT.md` to mention that the `sendmail` command is now a dependency of Ash-Nazg, and that it has to be configured properly?

Please add also the new config property `notifyFrom` to [`DEVELOPMENT.md`](https://github.com/w3c/ash-nazg/blob/master/DEVELOPMENT.md#setting-up).

If for some reason the e-mail addresses of contributors aren't returned by the GH API, `sendmail` fails, no e-mail is sent, and Ash-Nazg returns an error 500 to GH:

```
error:  Error: Sendmail exited with 64
    at ChildProcess.sendmailExit (/home/tripu/t/repo/ash-nazg/node_modules/nodemailer-sendmail-transport/src/sendmail-transport.js:111:28)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

Can you make it more robust?

(This isn't a theoretical concern: I wrestled with it for a while until I realised that it was failing because I have set &ldquo;don't show my e-mail address&rdquo; in [`https://github.com/settings/profile`](https://github.com/settings/profile). I removed it from my GH profile page to prevent spam, and I'm sure others will have it what way, too.)

**Comment by dontcallmedom** [comment]
@tripu pull request updated

**Pull request merged**
