### PR TITLE
improve color contrast ratio

### LINKED ISSUE #215: [accessibility] color contrast ratio
The [rendered pages](https://labs.w3.org/repo-manager/) use a redish/pinkish color (#F1648C) with white background (#FFFFFF). The resulting contrast ratio is 3:1, while the WCAG2 Level AA requirement is at least 4.5:1. A darker red (eg. #B13737) would meet the criteria but I don't have the design skills to judge color aesthetics.

### PR DESCRIPTION
**Pull request by deniak**
That PR addresses [@nitedog's suggestion](https://github.com/w3c/ash-nazg/issues/215). The screenshot below shows how it renders.

Screen Shot 2021-09-07 at 17 26 03

Fix #215

### CODE REVIEW

**Review by dontcallmedom — CHANGES_REQUESTED** [review]
the change should be done in the source file, app.css, rather than only in the minimized version (that would also make the change easier to review :)

**Comment by deniak** [comment]
> the change should be done in the source file, app.css, rather than only in the minimized version (that would also make the change easier to review :)

Indeed! Now done.

**Review by dontcallmedom — APPROVED** [review]

**Comment by nitedog** [comment]
I'm not able to do a full check. There are "color contrast analyzer" tools that can help you. Please also check different combinations and page states -- I think I spotted some green link text with red background on hover, which may not meet the requirement but I'm not sure where I saw that or how to find it.

**Comment by deniak** [comment]
Some elements were indeed using colors like `#84df5d` that don't pass the WCAG requirements.
Screen Shot 2021-09-07 at 18 29 32

I updated those as well. The other colors should work fine.

**Pull request merged**
