### PR TITLE
Make it possible to mark a PR as non substantive

### PR DESCRIPTION
**Pull request by dontcallmedom**

### CODE REVIEW

**Comment by plehegar** [comment]
Dom, you rock. There ought to be a meme for that.

**Comment by plehegar** [comment]
@tripu any ETA on deploying this?

**Comment by tripu** [comment]
(@plehegar, I'm afraid I *edited* your comment above inadvertently, instead of copying it to reply. Sorry about that!)

**Comment by plehegar** [comment]
the sooner the better imho

**Comment by dontcallmedom** [comment]
@plehegar it's already deployed now

**Pull request merged**
